name: CI - Build for project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Download dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        run: yarn db:generate
      
      - name: Build
        run: yarn build
